[package]
name = "bigmoe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.0"
seldom_pixel = "0.4.0"
bevy_framepace = "0.13.4"
time = "0.3.30"
